# Generated by Django 5.0.2 on 2024-04-30 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='producto',
            new_name='id_producto',
        ),
    ]
