# Generated by Django 5.0.2 on 2024-04-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_cart_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='device',
        ),
    ]
