# Generated by Django 5.0.2 on 2024-11-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_orden_cart_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='autor',
            field=models.CharField(default='Anonimo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='editorial',
            field=models.CharField(default='ND', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='pais',
            field=models.CharField(default='Mexico', max_length=50),
            preserve_default=False,
        ),
    ]
