# Generated by Django 5.0.2 on 2024-05-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_activo_cliente_device_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='whatsappa',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
